blueprint:
  name: Heizungssteuerung V1
  description: >
    Z2M-stabile Heizungssteuerung für Tuya/TRV602Z: Zeitplan (schedule) -> Komfort/Eco,
    optional Eco-Force, Fenster -> antifrost, Sommer/Winter (input_select),
    Sommer-Ventilübung (TRV-Boost), Party-Modus (Komfort erzwingen mit Countdown),
    optionale externe Kalibrierung (V5-Logik) und optionaler Manual-Override.
    Wichtig: Winterbetrieb nutzt hvac_mode=heat (damit TRV-internes Auto/Schedule NICHT greift).
    Keine unnötigen Writes: hvac/preset/setpoint nur bei Abweichung.
  domain: automation

  input:
    trvs:
      name: Heizungsregler
      selector:
        entity:
          domain: climate
          multiple: true

    schedule_entity:
      name: Zeitplan
      selector:
        entity:
          domain: schedule

    comfort_temp:
      name: Komfort-Temperatur (input_number)
      selector:
        entity:
          domain: input_number

    eco_temp:
      name: Eco-Temperatur (input_number)
      selector:
        entity:
          domain: input_number

    eco_force:
      name: Eco erzwingen (optional)
      default: []
      selector:
        entity:
          domain: input_boolean

    # ---------- Manual Override ----------
    manual_override_enabled:
      name: Manuelle TRV-Änderungen übernehmen
      default: false
      selector:
        boolean: {}

    manual_override_active:
      name: Helfer - Manual Override aktiv (optional)
      default: []
      selector:
        entity:
          domain: input_boolean

    manual_override_temp:
      name: Helfer - Manual Override Solltemp (optional)
      default: []
      selector:
        entity:
          domain: input_number

    # ---------- Party ----------
    party_boost_minutes:
      name: Party-Modus Dauer (Minuten) (optional)
      description: >-
        >0 erzwingt Komfort für diese Minuten (nur Winterbetrieb). Zählt automatisch herunter.
      default: []
      selector:
        entity:
          domain: input_number

    # ---------- Saison ----------
    season_mode:
      name: Saisonmodus (input_select)
      description: Muss die Optionen 'Winter' und 'Sommer' enthalten.
      selector:
        entity:
          domain: input_select

    summer_exercise_weekday:
      name: Sommermodus - Übung Wochentag
      default: sun
      selector:
        select:
          options:
            - label: Montag
              value: mon
            - label: Dienstag
              value: tue
            - label: Mittwoch
              value: wed
            - label: Donnerstag
              value: thu
            - label: Freitag
              value: fri
            - label: Samstag
              value: sat
            - label: Sonntag
              value: sun

    summer_exercise_time:
      name: Sommermodus - Übung Uhrzeit
      default: "12:00:00"
      selector:
        time: {}

    summer_boost_entity:
      name: Sommermodus - TRV Boost (Minuten) (optional)
      description: number.*boost_timeset_countdown (0..120 Minuten)
      default: []
      selector:
        entity:
          domain: number

    summer_boost_hold_seconds:
      name: Sommermodus - Boost Laufzeit (Sekunden)
      default: 30
      selector:
        number:
          min: 5
          max: 120
          step: 5
          mode: slider

    # ---------- Fenster ----------
    window_override_enabled:
      name: Fenstererkennung aktiv
      default: false
      selector:
        boolean: {}

    window_sensors:
      name: Fenstersensoren (0..n, optional)
      description: Wenn leer, wird das interne TRV-Window-Attribut genutzt.
      default: []
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    # ---------- Kalibrierung ----------
    enable_calibration:
      name: Kalibrierung aktivieren
      default: false
      selector:
        boolean: {}

    room_temperature_sensor:
      name: Raumthermometer (optional)
      default: []
      selector:
        entity:
          domain: sensor

    calibration_keyword:
      name: Kalibrier-Keyword
      default: local_temperature_calibration
      selector:
        text: {}

    calibration_delta:
      name: Kalibrier-Schwelle
      default: 0.5
      selector:
        number:
          min: 0.0
          max: 5.0
          step: 0.1
          mode: slider

    calibration_tick_minutes:
      name: Kalibrier-Intervall (Minuten)
      default: 5
      selector:
        number:
          min: 1
          max: 60
          step: 1
          mode: slider

    throttle_seconds:
      name: Mindestabstand Befehle
      default: 3
      selector:
        number:
          min: 0
          max: 300
          step: 1
          mode: slider

mode: restart

trigger:
  # Schedule: NUR echte Zustandswechsel (off->off Spam verhindern)
  - platform: state
    entity_id: !input schedule_entity
    from: "off"
    to: "on"
    id: schedule_on

  - platform: state
    entity_id: !input schedule_entity
    from: "on"
    to: "off"
    id: schedule_off

  - platform: state
    entity_id: !input comfort_temp
    id: comfort_changed

  - platform: state
    entity_id: !input eco_temp
    id: eco_changed

  - platform: state
    entity_id: !input eco_force
    id: eco_force_changed

  - platform: state
    entity_id: !input window_sensors
    id: window_changed

  - platform: state
    entity_id: !input season_mode
    id: season_changed

  - platform: state
    entity_id: !input party_boost_minutes
    id: party_value_changed

  # Manual Override: nur Solltemperatur-Änderung am TRV
  - platform: state
    entity_id: !input trvs
    attribute: temperature
    id: trv_setpoint_changed

  # Party-Countdown: jede Minute
  - platform: time_pattern
    minutes: "/1"
    id: party_tick

  # Kalibrierung: jede Minute triggern, aber nur alle X Minuten ausführen
  - platform: time_pattern
    minutes: "/1"
    id: calib_tick

  # Sommer-Ventilübung
  - platform: time
    at: !input summer_exercise_time
    id: summer_time

  - platform: homeassistant
    event: start
    id: ha_start

variables:
  trvs: !input trvs
  schedule_entity: !input schedule_entity
  comfort_entity: !input comfort_temp
  eco_entity: !input eco_temp
  eco_force_entity: !input eco_force

  manual_override_enabled: !input manual_override_enabled
  manual_override_active_entity: !input manual_override_active
  manual_override_temp_entity: !input manual_override_temp

  party_boost_minutes_entity: !input party_boost_minutes

  season_mode: !input season_mode
  summer_exercise_weekday: !input summer_exercise_weekday
  summer_boost_entity: !input summer_boost_entity
  summer_boost_hold_seconds: !input summer_boost_hold_seconds

  window_override_enabled: !input window_override_enabled
  window_sensors: !input window_sensors

  enable_calibration: !input enable_calibration
  room_temperature_sensor: !input room_temperature_sensor
  calibration_keyword: !input calibration_keyword
  calibration_delta: !input calibration_delta
  calibration_tick_minutes: !input calibration_tick_minutes

  throttle: !input throttle_seconds

  schedule_on: "{{ is_state(schedule_entity, 'on') }}"
  comfort_value: "{{ states(comfort_entity) | float(20) }}"
  eco_value: "{{ states(eco_entity) | float(18) }}"

  eco_forced_on: >-
    {{ eco_force_entity is string and eco_force_entity|length > 0 and is_state(eco_force_entity,'on') }}

  is_summer: "{{ is_state(season_mode, 'Sommer') }}"
  today_wd: "{{ now().strftime('%a') | lower }}"
  is_exercise_day: "{{ today_wd == summer_exercise_weekday }}"

  party_minutes: >-
    {% if party_boost_minutes_entity is string and party_boost_minutes_entity|length > 0 %}
      {{ states(party_boost_minutes_entity) | int(0) }}
    {% else %}
      0
    {% endif %}
  party_active: "{{ (not is_summer) and (party_minutes | int(0) > 0) }}"

  manual_override_on: >-
    {{ manual_override_enabled
       and manual_override_active_entity is string and manual_override_active_entity|length > 0
       and is_state(manual_override_active_entity,'on') }}

  manual_override_value: >-
    {% if manual_override_temp_entity is string and manual_override_temp_entity|length > 0 %}
      {% set s = states(manual_override_temp_entity) %}
      {% if s in ['unknown','unavailable','none','None',''] %}
        {{ none }}
      {% else %}
        {{ s | float(none) }}
      {% endif %}
    {% else %}
      {{ none }}
    {% endif %}

  window_open: >-
    {% if not window_override_enabled %}
      false
    {% elif window_sensors | length > 0 %}
      {{ window_sensors | select('is_state','on') | list | length > 0 }}
    {% else %}
      {% set open_found = false %}
      {% for t in trvs %}
        {% if state_attr(t,'window') in ['OPEN','open',true,1] %}
          {% set open_found = true %}
        {% endif %}
      {% endfor %}
      {{ open_found }}
    {% endif %}

  external_temp: >-
    {% if room_temperature_sensor is string and room_temperature_sensor|length > 0 %}
      {% set s = states(room_temperature_sensor) %}
      {% if s in ['unknown','unavailable','none','None',''] %}
        {{ none }}
      {% else %}
        {{ s | float(none) }}
      {% endif %}
    {% else %}
      {{ none }}
    {% endif %}

  calib_due: >-
    {% set m = calibration_tick_minutes | int(5) %}
    {{ (now().minute % (m if m > 0 else 5)) == 0 }}

  # Basis-Zieltemperatur (Schedule + Eco-Force)
  base_target: >-
    {% if eco_forced_on %}
      {{ eco_value }}
    {% elif schedule_on %}
      {{ comfort_value }}
    {% else %}
      {{ eco_value }}
    {% endif %}

  # Zieltemperatur nach Priorität (Party > EcoForce > Manual > Schedule/Eco)
  target_temperature: >-
    {% if party_active %}
      {{ comfort_value }}
    {% elif eco_forced_on %}
      {{ eco_value }}
    {% elif manual_override_on and (manual_override_value is not none) %}
      {{ manual_override_value }}
    {% else %}
      {{ base_target }}
    {% endif %}

action:
  - delay:
      seconds: "{{ throttle }}"

  # ---- party_tick darf NICHT in Normalbetrieb fallen, wenn Party aus ----
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'party_tick' and not party_active }}"
        sequence:
          - stop: "party_tick ohne Party -> nichts tun"

  # ---- calib_tick nur alle X Minuten ausführen; sonst sofort STOP ----
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'calib_tick' and (not calib_due or not enable_calibration) }}"
        sequence:
          - stop: "calib_tick nicht fällig/aus -> nichts tun"

  # ---- Manual Override merken (TRV manuell drehen) ----
  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{ trigger.id == 'trv_setpoint_changed'
                 and manual_override_enabled
                 and (not is_summer)
                 and (manual_override_active_entity is string and manual_override_active_entity|length > 0)
                 and (manual_override_temp_entity is string and manual_override_temp_entity|length > 0)
                 and trigger.to_state is not none and trigger.from_state is not none
                 and (trigger.to_state.context.parent_id != this.context.id) }}
        sequence:
          - service: input_number.set_value
            target:
              entity_id: "{{ manual_override_temp_entity }}"
            data:
              value: "{{ trigger.to_state.attributes.temperature | float }}"
          - service: input_boolean.turn_on
            target:
              entity_id: "{{ manual_override_active_entity }}"

  # ---- Manual Override reset beim nächsten Schedule-Wechsel ----
  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{ (trigger.id in ['schedule_on','schedule_off'])
                 and (manual_override_active_entity is string and manual_override_active_entity|length > 0) }}
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: "{{ manual_override_active_entity }}"

  # ---- Sommer-Ventilübung (nur Sommer, nur zur Uhrzeit) ----
  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{ trigger.id == 'summer_time'
                 and is_summer and is_exercise_day
                 and (summer_boost_entity is string and summer_boost_entity|length > 0) }}
        sequence:
          - service: number.set_value
            target:
              entity_id: "{{ summer_boost_entity }}"
            data:
              value: 1
          - delay:
              seconds: "{{ summer_boost_hold_seconds | int(30) }}"
          - service: number.set_value
            target:
              entity_id: "{{ summer_boost_entity }}"
            data:
              value: 0
          - stop: "Sommer: Ventilübung"

  # ---- Sommer: komplett aus (nur wenn nicht schon off) ----
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ is_summer }}"
        sequence:
          - repeat:
              for_each: "{{ trvs }}"
              sequence:
                - variables:
                    trv: "{{ repeat.item }}"
                - choose:
                    - conditions:
                        - condition: template
                          value_template: "{{ states(trv) != 'off' }}"
                      sequence:
                        - service: climate.set_hvac_mode
                          target:
                            entity_id: "{{ trv }}"
                          data:
                            hvac_mode: off
          - stop: "Sommer: OFF"

  # ---- Fenster offen: Frostschutz (antifrost) ----
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ window_open }}"
        sequence:
          - repeat:
              for_each: "{{ trvs }}"
              sequence:
                - variables:
                    trv: "{{ repeat.item }}"
                    hvac: "{{ states(trv) }}"
                    preset: "{{ state_attr(trv,'preset_mode') }}"
                # antifrost funktioniert zuverlässig, wenn hvac nicht off ist -> heat
                - choose:
                    - conditions:
                        - condition: template
                          value_template: "{{ hvac == 'off' }}"
                      sequence:
                        - service: climate.set_hvac_mode
                          target:
                            entity_id: "{{ trv }}"
                          data:
                            hvac_mode: heat
                - choose:
                    - conditions:
                        - condition: template
                          value_template: "{{ preset != 'antifrost' }}"
                      sequence:
                        - service: climate.set_preset_mode
                          target:
                            entity_id: "{{ trv }}"
                          data:
                            preset_mode: antifrost
          - stop: "Fenster: Frostschutz"

  # ---- Party Countdown (nur wenn Party aktiv und party_tick) ----
  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{ trigger.id == 'party_tick'
                 and party_active
                 and (party_boost_minutes_entity is string and party_boost_minutes_entity|length > 0) }}
        sequence:
          - service: number.set_value
            target:
              entity_id: "{{ party_boost_minutes_entity }}"
            data:
              value: "{{ [0, party_minutes - 1] | max }}"

  # ---- Kalibrierung (V5-Logik) nur wenn fällig ----
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ enable_calibration and external_temp is not none and calib_due }}"
        sequence:
          - repeat:
              for_each: "{{ trvs }}"
              sequence:
                - variables:
                    trv: "{{ repeat.item }}"
                    trv_temp: "{{ state_attr(trv,'current_temperature') | float(none) }}"
                    dev_id: "{{ device_id(trv) }}"
                    cal_entity: >-
                      {% set ents = device_entities(dev_id) | list %}
                      {% set nums = ents | select('match','^number\\.') | list %}
                      {% set hits = nums | select('search', calibration_keyword) | list %}
                      {{ hits | first | default(none) }}
                    old_offset: "{{ states(cal_entity) | float(0) if cal_entity else none }}"
                    step: "{{ state_attr(cal_entity,'step') | float(1) if cal_entity else 1 }}"
                    diff: "{{ external_temp - trv_temp if trv_temp is not none else none }}"
                    new_offset: "{{ (old_offset + diff) if diff is not none else none }}"
                    rounded: "{{ ((new_offset / step) | round(0) * step) if new_offset is not none else none }}"
                - choose:
                    - conditions:
                        - condition: template
                          value_template: "{{ cal_entity and diff is not none and (diff | abs) >= calibration_delta }}"
                      sequence:
                        - service: number.set_value
                          target:
                            entity_id: "{{ cal_entity }}"
                          data:
                            value: "{{ rounded }}"

  # ---- Normalbetrieb Winter: hvac_mode=heat (damit TRV-internes Auto/Schedule NICHT greift) ----
  - repeat:
      for_each: "{{ trvs }}"
      sequence:
        - variables:
            trv: "{{ repeat.item }}"
            hvac: "{{ states(trv) }}"
            preset: "{{ state_attr(trv,'preset_mode') }}"
            current_set: "{{ state_attr(trv,'temperature') | float(none) }}"
            desired_temp: "{{ target_temperature | float }}"
        # Winter: hvac_mode heat (nur wenn abweichend)
        - choose:
            - conditions:
                - condition: template
                  value_template: "{{ hvac != 'heat' }}"
              sequence:
                - service: climate.set_hvac_mode
                  target:
                    entity_id: "{{ trv }}"
                  data:
                    hvac_mode: heat
        # preset zurück auf auto (nur wenn nötig)
        - choose:
            - conditions:
                - condition: template
                  value_template: "{{ preset is not none and preset != 'auto' }}"
              sequence:
                - service: climate.set_preset_mode
                  target:
                    entity_id: "{{ trv }}"
                  data:
                    preset_mode: auto
        # setpoint nur wenn wirklich abweichend
        - choose:
            - conditions:
                - condition: template
                  value_template: "{{ current_set is none or (current_set - desired_temp) | abs >= 0.1 }}"
              sequence:
                - service: climate.set_temperature
                  target:
                    entity_id: "{{ trv }}"
                  data:
                    temperature: "{{ desired_temp }}"
```0
