blueprint:
  name: Heizungssteuerung V2
  description: >
    Neuaufbau (V2) – klare Prioritäten, kein Auto-Modus (nur heat/off),
    Schedule->Komfort/Eco, Eco erzwingen, Sommer/Winter, Fenster->Frostschutz (5°C),
    manuelle TRV-Sollwertänderung übernimmt Eco- oder Komfort-Helfer (ereignisgesteuert),
    externe Temperatur-Kalibrierung wie V5 (nur wenn |Diff| > 0,2°C).

    Priorität:
    1) Sommer -> OFF (niemals heizen)
    2) Fenster offen -> Frostschutz (heat + 5°C, optional antifrost)
    3) Winter -> heat + (EcoForce ? Eco : (Schedule ? Komfort : Eco))

  domain: automation

  input:
    trvs:
      name: Heizkörperthermostat(e)
      selector:
        entity:
          domain: climate
          multiple: true

    schedule_entity:
      name: Zeitplan (Schedule)
      selector:
        entity:
          domain: schedule

    comfort_temp:
      name: Komfort-Temperatur (Helfer)
      selector:
        entity:
          domain: input_number

    eco_temp:
      name: Eco-Temperatur (Helfer)
      selector:
        entity:
          domain: input_number

    eco_force:
      name: Eco erzwingen (optional)
      default: []
      selector:
        entity:
          domain: input_boolean

    season_mode:
      name: Sommer/Winter (input_select)
      description: Muss die Optionen 'Sommer' und 'Winter' enthalten.
      selector:
        entity:
          domain: input_select

    window_override_enabled:
      name: Fensterlogik aktiv
      default: false
      selector:
        boolean: {}

    window_sensors:
      name: Fenstersensor(en) (optional, 0..n)
      description: Wenn leer, wird (falls vorhanden) TRV-Attribut 'window' genutzt.
      default: []
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    frost_temperature:
      name: Frostschutz-Temperatur
      default: 5
      selector:
        number:
          min: 5
          max: 12
          step: 0.5
          mode: slider

    enable_calibration:
      name: Externe Temperatur-Kalibrierung aktiv
      default: false
      selector:
        boolean: {}

    room_temperature_sensor:
      name: Externer Temperatursensor (optional)
      default: []
      selector:
        entity:
          domain: sensor

    calibration_keyword:
      name: Kalibrier-Keyword (Number-Entity am TRV)
      default: local_temperature_calibration
      selector:
        text: {}

    calibration_delta:
      name: Kalibrier-Schwelle (°C)
      default: 0.2
      selector:
        number:
          min: 0.0
          max: 2.0
          step: 0.1
          mode: slider

    calibration_tick_minutes:
      name: Kalibrier-Intervall (Minuten)
      default: 5
      selector:
        number:
          min: 1
          max: 60
          step: 1
          mode: slider

    throttle_seconds:
      name: Mindestabstand Befehle (Sekunden)
      default: 2
      selector:
        number:
          min: 0
          max: 30
          step: 1
          mode: slider

mode: restart

trigger:
  # Schedule NUR bei echten Zustandswechseln (verhindert Spam)
  - platform: state
    entity_id: !input schedule_entity
    from: "off"
    to: "on"
    id: schedule_on

  - platform: state
    entity_id: !input schedule_entity
    from: "on"
    to: "off"
    id: schedule_off

  - platform: state
    entity_id: !input eco_force
    id: eco_force_changed

  - platform: state
    entity_id: !input season_mode
    id: season_changed

  - platform: state
    entity_id: !input window_sensors
    id: window_changed

  - platform: state
    entity_id: !input comfort_temp
    id: comfort_changed

  - platform: state
    entity_id: !input eco_temp
    id: eco_changed

  # Manuelle Sollwertänderung am TRV (App oder Drehen)
  - platform: state
    entity_id: !input trvs
    attribute: temperature
    id: trv_setpoint_changed

  # Kalibrierung: Tick (wir führen nur alle X Minuten aus)
  - platform: time_pattern
    minutes: "/1"
    id: calib_tick

  - platform: homeassistant
    event: start
    id: ha_start

variables:
  trvs: !input trvs
  schedule_entity: !input schedule_entity
  comfort_entity: !input comfort_temp
  eco_entity: !input eco_temp
  eco_force_entity: !input eco_force
  season_mode: !input season_mode
  window_override_enabled: !input window_override_enabled
  window_sensors: !input window_sensors
  frost_temperature: !input frost_temperature
  enable_calibration: !input enable_calibration
  room_temperature_sensor: !input room_temperature_sensor
  calibration_keyword: !input calibration_keyword
  calibration_delta: !input calibration_delta
  calibration_tick_minutes: !input calibration_tick_minutes
  throttle: !input throttle_seconds

  is_summer: "{{ is_state(season_mode, 'Sommer') }}"
  schedule_on: "{{ is_state(schedule_entity, 'on') }}"

  eco_forced_on: >-
    {{ eco_force_entity is string and eco_force_entity|length > 0 and is_state(eco_force_entity,'on') }}

  comfort_value: "{{ states(comfort_entity) | float(20) }}"
  eco_value: "{{ states(eco_entity) | float(18) }}"

  # Fenster offen? Externe Sensoren sonst internes TRV-Attribut window
  window_open: >-
    {% if not window_override_enabled %}
      false
    {% elif window_sensors | length > 0 %}
      {{ window_sensors | select('is_state','on') | list | length > 0 }}
    {% else %}
      {% set open_found = false %}
      {% for t in trvs %}
        {% if state_attr(t,'window') in ['OPEN','open',true,1] %}
          {% set open_found = true %}
        {% endif %}
      {% endfor %}
      {{ open_found }}
    {% endif %}

  # gewünschte Temperatur (Winterbetrieb, wenn kein Fenster)
  desired_temp: >-
    {% if eco_forced_on %}
      {{ eco_value }}
    {% elif schedule_on %}
      {{ comfort_value }}
    {% else %}
      {{ eco_value }}
    {% endif %}

  external_temp: >-
    {% if room_temperature_sensor is string and room_temperature_sensor|length > 0 %}
      {% set s = states(room_temperature_sensor) %}
      {% if s in ['unknown','unavailable','none','None',''] %}
        {{ none }}
      {% else %}
        {{ s | float(none) }}
      {% endif %}
    {% else %}
      {{ none }}
    {% endif %}

  calib_due: >-
    {% set m = calibration_tick_minutes | int(5) %}
    {{ (now().minute % (m if m > 0 else 5)) == 0 }}

action:
  - delay:
      seconds: "{{ throttle }}"

  # =========================
  # 1) Manuelle Sollwertänderung übernehmen -> Helfer aktualisieren -> STOP
  # =========================
  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{ trigger.id == 'trv_setpoint_changed'
                 and trigger.to_state is not none
                 and trigger.from_state is not none
                 and (trigger.to_state.attributes.temperature != trigger.from_state.attributes.temperature)
                 and (trigger.to_state.context.parent_id != this.context.id) }}
        sequence:
          - variables:
              new_setpoint: "{{ trigger.to_state.attributes.temperature | float }}"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ eco_forced_on or (not schedule_on) }}"
                sequence:
                  - service: input_number.set_value
                    target:
                      entity_id: "{{ eco_entity }}"
                    data:
                      value: "{{ new_setpoint }}"
              - conditions:
                  - condition: template
                    value_template: "{{ schedule_on and (not eco_forced_on) }}"
                sequence:
                  - service: input_number.set_value
                    target:
                      entity_id: "{{ comfort_entity }}"
                    data:
                      value: "{{ new_setpoint }}"
          - stop: "Manueller TRV-Sollwert übernommen (Eco/Kommfort) – kein Übersteuern"

  # =========================
  # 2) Kalibrierung nur wenn fällig (V5-Logik)
  # =========================
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'calib_tick' and (not enable_calibration or not calib_due or external_temp is none) }}"
        sequence:
          - stop: "Kalibrierung nicht fällig/aus"

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ enable_calibration and calib_due and external_temp is not none }}"
        sequence:
          - repeat:
              for_each: "{{ trvs }}"
              sequence:
                - variables:
                    trv: "{{ repeat.item }}"
                    trv_temp: "{{ state_attr(trv,'current_temperature') | float(none) }}"
                    dev_id: "{{ device_id(trv) }}"
                    cal_entity: >-
                      {% set ents = device_entities(dev_id) | list %}
                      {% set nums = ents | select('match','^number\\.') | list %}
                      {% set hits = nums | select('search', calibration_keyword) | list %}
                      {{ hits | first | default(none) }}
                    old_offset: >-
                      {% if cal_entity %}
                        {% set x = states(cal_entity) %}
                        {% if x in ['unknown','unavailable','none','None',''] %}
                          0
                        {% else %}
                          {{ x | float(0) }}
                        {% endif %}
                      {% else %}
                        {{ none }}
                      {% endif %}
                    step: "{{ state_attr(cal_entity,'step') | float(0.1) if cal_entity else 0.1 }}"
                    diff: "{{ (external_temp - trv_temp) if (trv_temp is not none) else none }}"
                    new_offset: "{{ (old_offset + diff) if (diff is not none and old_offset is not none) else none }}"
                    rounded: "{{ ((new_offset / step) | round(0) * step) if (new_offset is not none) else none }}"
                - choose:
                    - conditions:
                        - condition: template
                          value_template: "{{ cal_entity and diff is not none and (diff | abs) > (calibration_delta | float(0.2)) }}"
                      sequence:
                        - service: number.set_value
                          target:
                            entity_id: "{{ cal_entity }}"
                          data:
                            value: "{{ rounded }}"

  # =========================
  # 3) Sommer/Winter + Fenster + Normalbetrieb
  # =========================

  # Sommer: strikt OFF
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ is_summer }}"
        sequence:
          - repeat:
              for_each: "{{ trvs }}"
              sequence:
                - variables:
                    trv: "{{ repeat.item }}"
                - choose:
                    - conditions:
                        - condition: template
                          value_template: "{{ states(trv) != 'off' }}"
                      sequence:
                        - service: climate.set_hvac_mode
                          target:
                            entity_id: "{{ trv }}"
                          data:
                            hvac_mode: off
          - stop: "Sommermodus aktiv -> OFF"

  # Fenster offen: Frostschutz (heat + 5°C, optional preset antifrost)
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ window_open }}"
        sequence:
          - repeat:
              for_each: "{{ trvs }}"
              sequence:
                - variables:
                    trv: "{{ repeat.item }}"
                    hvac: "{{ states(trv) }}"
                    preset: "{{ state_attr(trv,'preset_mode') }}"
                    current_set: "{{ state_attr(trv,'temperature') | float(none) }}"
                    frost: "{{ frost_temperature | float(5) }}"
                - choose:
                    - conditions:
                        - condition: template
                          value_template: "{{ hvac != 'heat' }}"
                      sequence:
                        - service: climate.set_hvac_mode
                          target:
                            entity_id: "{{ trv }}"
                          data:
                            hvac_mode: heat
                - choose:
                    - conditions:
                        - condition: template
                          value_template: "{{ preset is not none and preset != 'antifrost' }}"
                      sequence:
                        - service: climate.set_preset_mode
                          target:
                            entity_id: "{{ trv }}"
                          data:
                            preset_mode: antifrost
                - choose:
                    - conditions:
                        - condition: template
                          value_template: "{{ current_set is none or (current_set - frost) | abs >= 0.1 }}"
                      sequence:
                        - service: climate.set_temperature
                          target:
                            entity_id: "{{ trv }}"
                          data:
                            temperature: "{{ frost }}"
          - stop: "Fenster offen -> Frostschutz"

  # Winter normal: IMMER heat, NIE auto. Temperatur nur bei Abweichung setzen.
  - repeat:
      for_each: "{{ trvs }}"
      sequence:
        - variables:
            trv: "{{ repeat.item }}"
            hvac: "{{ states(trv) }}"
            current_set: "{{ state_attr(trv,'temperature') | float(none) }}"
            target: "{{ desired_temp | float }}"
        - choose:
            - conditions:
                - condition: template
                  value_template: "{{ hvac != 'heat' }}"
              sequence:
                - service: climate.set_hvac_mode
                  target:
                    entity_id: "{{ trv }}"
                  data:
                    hvac_mode: heat
        - choose:
            - conditions:
                - condition: template
                  value_template: "{{ current_set is none or (current_set - target) | abs >= 0.1 }}"
              sequence:
                - service: climate.set_temperature
                  target:
                    entity_id: "{{ trv }}"
                  data:
                    temperature: "{{ target }}"
